name: pardner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


      

flutter:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Italic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Variable.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-VariableItalic.ttf
          style: italic
    - family: Cabinet
      fonts:
        - asset: assets/fonts/CabinetGrotesk-Black.ttf
          weight: 800
        - asset: assets/fonts/CabinetGrotesk-Bold.ttf
          weight: 600
        - asset: assets/fonts/CabinetGrotesk-Extrabold.ttf
          weight: 700
        - asset: assets/fonts/CabinetGrotesk-Extralight.ttf
          weight: 200
        - asset: assets/fonts/CabinetGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/CabinetGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/CabinetGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/CabinetGrotesk-Thin.ttf
          weight: 100
        - asset: assets/fonts/CabinetGrotesk-Variable.ttf
          weight: 900
  uses-material-design: true
