name: pardner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  
  
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.17
  hooks_riverpod: ^2.6.1
  objectbox: ^4.0.3
  
  
  objectbox_sync_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  smooth_page_indicator: ^1.2.0+3
  uuid: ^4.5.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  objectbox_generator: any
  riverpod_generator: ^2.6.3
  
  


      

flutter:
  assets:
    - assets/illustrations/svg/
    - assets/illustrations/png/
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Italic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Variable.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-VariableItalic.ttf
          style: italic
    - family: Cabinet
      fonts:
        - asset: assets/fonts/CabinetGrotesk-Black.ttf
          weight: 800
        - asset: assets/fonts/CabinetGrotesk-Bold.ttf
          weight: 600
        - asset: assets/fonts/CabinetGrotesk-Extrabold.ttf
          weight: 700
        - asset: assets/fonts/CabinetGrotesk-Extralight.ttf
          weight: 200
        - asset: assets/fonts/CabinetGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/CabinetGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/CabinetGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/CabinetGrotesk-Thin.ttf
          weight: 100
        - asset: assets/fonts/CabinetGrotesk-Variable.ttf
          weight: 900
  uses-material-design: true
